version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
      - "9300"
  logstash:
    image: "docker.elastic.co/logstash/logstash:7.6.2"
    command: "bin/logstash -f pipeline/vep.config --config.reload.automatic"
    volumes:
      - ./services/variation-service/pipeline/:/usr/share/logstash/pipeline/
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.6.2"
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
