version: '3.7'
services:
  gateway:
    image: "node:12"
    working_dir: /home/node/app
    volumes:
      - ./gateway:/home/node/app:ro
      - gateway-node-modules-volume:/home/node/app/node_modules
    ports:
      - "9016:4000"
    command: >
      bash -c "npm ci && npm run start"
    depends_on:
      - variation-service
      - phenotype-annotation-service

  variation-service:
    image: "node:12"
    working_dir: /home/node/app
    volumes:
      - ./services/variation-service:/home/node/app:ro
      - variation-service-node-modules-volume:/home/node/app/node_modules
    expose:
      - "4000"
    command: >
      bash -c "npm ci && npm run start"
    depends_on:
      - elasticsearch

  phenotype-annotation-service:
    image: "node:12"
    working_dir: /home/node/app
    volumes:
      - ./services/phenotype-annotation-service:/home/node/app:ro
      - phenotype-annotation-service-node-modules-volume:/home/node/app/node_modules
    expose:
      - "4000"
    command: >
      bash -c "npm ci && npm run start"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
      - "9300"

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.6.2"
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
  gateway-node-modules-volume:
  variation-service-node-modules-volume:
  phenotype-annotation-service-node-modules-volume:
