version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
      - "9300"
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.6.2"
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch-data:
