- pipeline.id: alleles
  path.config: "pipeline/alleles.config"
- pipeline.id: phenotype_annotations
  path.config: "pipeline/phenotype_annotation.config"
- pipeline.id: vep
  path.config: "pipeline/vep.config"
- pipeline.id: variants
  path.config: "pipeline/variants.config"
- pipeline.id: dlq
  path.config: "pipeline/dlq.config"
